version: "3"
services:
  postgres:
    image: postgres
    container_name: pdf_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: FilePDF
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - .data/docker/postgres:/var/lib/postgresql/data

  minio:
    image: quay.io/storage/storage
    container_name: pdf_minio
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - .data/docker/storage:/data
    command: server /data --console-address ":9090"

#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#
#  kafka:
#    image: confluentinc/cp-kafka:7.0.0
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - 9092:9092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  kafdrop:
#    image: obsidiandynamics/kafdrop:latest
#    container_name: kafdrop
#    depends_on:
#      - kafka
#    ports:
#      - 19000:9000
#    environment:
#      KAFKA_BROKERCONNECT: kafka:29092

#  mongo:
#    image: mongo:4.4.4
#    container_name: mongo
#    restart: always
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: s3cr3t
#      MONGO_INITDB_DATABASE: test_name
#    volumes:
#      - .data/docker/mongodb:/data/db
#
#  mongo-express:
#    image: mongo-express:0.54
#    container_name: mongo_express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: s3cr3t